# Generated by Django 5.0.6 on 2024-06-19 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, max_length=5000, null=True)),
                ('useremail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.userprofile')),
            ],
        ),
    ]
